# Generated by Django 6.0.5 on 2026-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('chef', 'Chef'), ('cashier', 'Cashier')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_addons',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='orders.addon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_addons',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='orders.addon'),
        ),
    ]
