# Generated by Django 6.0.5 on 2026-05-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_addon_alter_user_role_menuitem_available_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
