# Generated by Django 6.0.5 on 2026-05-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready')], default='preparing', max_length=15),
        ),
    ]
